CC=gcc
CFLAGS=-Wall
conversion: conversion.c conversion.h
	$(CC) $(CFLAGS) conversion.c -o main 
	./main


# Makefile.
# Archivos header (.h).
# Tipo de dato double.
# Funciones.
# Pruebas unitarias.
# assert.
# Interfaces e Implementación.