CC=gcc
CFLAGS=-Wall
conversion: conversion.c conversion.h
	$(CC) $(CFLAGS) -o main tablasDeConversion.c conversion.c 
	./main

test: conversionTest.c conversion.h
	$(CC) $(CFLAGS) -o test conversionTest.c conversion.c 
	./test



# Makefile.
# Archivos header (.h).
# Tipo de dato double.
# Funciones.
# Pruebas unitarias.
# assert.
# Interfaces e Implementación.