# Makes FahrCel.exe
# JMS
# 2016
# K&R Exercise 1.15. Rewrite the temperature conversion program
# of Section 1.2 to use a function for conversion.


CC=gcc
CFLAGS=-Wall
main: main.c
	$(CC) $(CFLAGS) main.c -o main 
	./main