CC=gcc
CFLAGS=-Wall
Conversion: Conversion.c
	$(CC) $(CFLAGS) Conversion.c -o main 
	./main


# Makefile.
# Archivos header (.h).
# Tipo de dato double.
# Funciones.
# Pruebas unitarias.
# assert.
# Interfaces e Implementación.